name: crypto_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animated_splash_screen: ^1.1.0
  curved_navigation_bar: ^1.0.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^0.23.0+1
  glass_kit: ^2.0.1
  google_sign_in: ^5.2.3
  http: ^0.13.4
  in_app_purchase: ^2.0.1
  provider: ^6.0.1
  syncfusion_flutter_datagrid: ^19.3.46

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/buttons/
